### ISSUE TITLE
Typo in redcap_every_page_top ?

### ISSUE THREAD

**Issue by aarenson** [grezniczek/redcap_javascript_injector#1]
Is the following code correct? I would think that you would want to inject type 'aer' on the add/edit records page.  From line 29-34 in ExternalModule.php

```
       else if (PAGE === "DataEntry/record_home.php" && !isset($_GET["id"])) {
            $this->injectJS("aer", null);
        }
        else if (PAGE === "DataEntry/record_home.php" && isset($_GET["id"])) {
            $this->injectJS("rhp", null);
        }
```

**Comment by grezniczek** [comment]
Hey @aarenson, only seeing this now ... for some reason watch was turned off ..

No, the code is correct. The _Add / Edit Records_ page (aer) is "DataEntry/record_home.php" **without** a record id, while the same address **with** a record id is the _Record Home Page_ (rhp).
