### ISSUE TITLE
Java Injection in fields on survey

### ISSUE THREAD

**Issue by Tokols** [grezniczek/redcap_javascript_injector#10]
Hi,

I could use a javascript function that operates on specific forms on my survey pages.
So I need the code to trigger after a certain data entry has been made and then delete the entry from the record in a second step.
In the meanwhile the entered data is piped into another project and saved there.

Is this possible with your current module already or would it be possible to adjust the module in that way in the future?

Kind regards,
TK

**Comment by grezniczek** [comment]
This is beyond the scope of the module. 

But you can inject ANY JS with it (or trigger loading of more JS). So anything is possible. But that's up to you.
(Sorry for the late response)
