### ISSUE TITLE
Error log getting full on dev  server

### ISSUE THREAD

**Issue by jthomas08** [grezniczek/redcap_javascript_injector#12]
Error message: Only variables should be passed by reference, File: /var/www/virtualhosts/stage-redcap/modules/redcap_javascript_injector_v2.1.0/JSInjectorExternalModule.php, Line: 342

**Comment by grezniczek** [comment]
@jthomas08 - Thanks for letting me know. Fixed in v2.1.1 (already submitted to the Repository).
