### ISSUE TITLE
Enhancement: Inject js on EM pages

### ISSUE THREAD

**Issue by aboulang** [grezniczek/redcap_javascript_injector#13]
I have a use for injecting JS into an EM page.   Can that be supported? I want to integrate an existing EM with other customizations I am doing. This is so I don't have to reproduce the functionality of the EM but build on it --  in my case pass some URL parameters to the EM to populate fields in the EM page and fire off a click event in it.

**Comment by grezniczek** [comment]
@aboulang You can already do this. Simply enable the JS Injector for "All project pages" and limit the actions you want to be performed to the EM plugin page by querying, e.g., the location for prefix and page. To limit injection as much as possible, set all available page options to "Always off".
