### ISSUE TITLE
Make snippet super-users-only

### ISSUE THREAD

**Issue by lsgs** [grezniczek/redcap_javascript_injector#2]
Great module @grezniczek. I'm wondering whether you've considered making the JS snippet field super-users-only in config.json?

**Comment by grezniczek** [comment]
Hey @lsgs - Should it be? To change the module config, a user has to have design rights in a project, and the JavaScript snippets are only ever injected in the project context. If they break it, they own it.
Where would you see the benefit of this being super-user only?

**Comment by grezniczek** [comment]
How about adding a system setting that can be turned on to limit access to the project configuration to super users only? That wouldn't break anything. I guess that would be a good addition.

**Comment by grezniczek** [comment]
#3 adds this option. Will that do? I'll submit this to the Repo as [v1.1.2](https://github.com/grezniczek/redcap_javascript_injector/tree/v1.1.2).

Closing this. Feel free to re-open if necessary.
