### ISSUE TITLE
Injection on survey queue page

### ISSUE THREAD

**Issue by fhosking** [grezniczek/redcap_javascript_injector#4]
Currently it is possible to inject javascript onto the following types of pages:

![image](https://user-images.githubusercontent.com/69717469/97727246-1d29eb80-1ac8-11eb-9a1f-27b944e18c2f.png)

I was wondering if it would be possible to use this extention to also inject to the survey queue page. This would be really useful feature for survey queue customisation.

**Comment by grezniczek** [comment]
@fhosking - Without trying it ... I'd guess that you should be able to use the "All project pages" option (and check in JS what the page actually is).
However, such a specifier would certainly be useful. Not sure when I would get to adding this, but PRs are of course welcome.

**Comment by fhosking** [comment]
It works on all project pages! I would love to be able to suggest a PR but i'm too much of a beginner programmer at the moment. Thanks, I'm a big fan of this extention.
