### ISSUE TITLE
Option to inject late (bottom)

### ISSUE THREAD

**Issue by aboulang** [grezniczek/redcap_javascript_injector#5]
There are use cases when it makes sense to inject late in the game  -- for instance to use querySelector to modify existing elements on a page. Can this option be added?

**Comment by grezniczek** [comment]
@aboulang Simply wrap your code in the JQuery ready function or use a timeout, or both.
```JS
$(function() {
// will execute when the page is ready
});

setTimeout(function() {
// executes after 1 second
}, 1000);
```

Alternatively, you could wait until a certain situation is present by using `setInterval`. Once your criteria are satisfied, cancel the interval and do your thing. Please search the Internet on how to best implement such an approach.
