### ISSUE TITLE
Error occurred when configure with RedCap v11.2.2

### ISSUE THREAD

**Issue by anoop-singh-dev** [grezniczek/redcap_javascript_injector#6]
When I try to configure RedCap javascript injector (v1.1.3) with RedCAp v11.2.2 it gives the below error

![oie_TSgBQEQeyoOb](https://user-images.githubusercontent.com/9657488/148883357-4ab84a09-7792-40fc-a847-a537f804d1e5.png)

**Comment by grezniczek** [comment]
I don't see this in the latest REDCap version, and this error message is too little to go on, unfortunately. 
From your screenshot, it seems that the REDCap JS Injector is the only module. Does this happen for others, too?

**Comment by anoop-singh-dev** [comment]
@grezniczek I add REDCap CSS Injector it happened with it also. You can see it in the below video link

https://watch.screencastify.com/v/AWLHY8FRZzyxRSZexxWk

**Comment by grezniczek** [comment]
This confirms that this is an error with the EM framework or your configuration.
I would suggest to upgrade REDCap to a newer version. 11.2.2 is quite dated and not supported any longer.
