### ISSUE TITLE
Not injecting all surveys

### ISSUE THREAD

**Issue by fhosking** [grezniczek/redcap_javascript_injector#9]
Hi there. I am enjoying the additional features of the injector 2.0. I feel like i am a heavy user. However I think I might have found an issue:

I am using the following setup:

![image](https://user-images.githubusercontent.com/69717469/222172048-7cae881b-1e68-4354-a0b1-4da98e52ddac.png)

However, on one of my surveys (I have 36 that all need the same code) this does not produce a result:

![image](https://user-images.githubusercontent.com/69717469/222172349-4aaeb14e-f820-4907-ab69-95e79c6d6afc.png)

Although when i select a specific instrument:

![image](https://user-images.githubusercontent.com/69717469/222172585-097aef27-8d5a-4c61-8fe0-fbff57935272.png)

I now do get a result:

![image](https://user-images.githubusercontent.com/69717469/222172768-4247491a-b5a0-40b4-9b00-858b55a7f57b.png)

I feel like this issue occured after the upgrade from v.1.X to v2.0. I think previously, blank instrument meant -> "load on all instruments". This is a good feature because manually clicking on all instruments in a project sometimes isn't viable. Perhaps the blank functionality should return, or a specific 'On on all instruments' option should be available on the dropdown?

Thanks,

Feargus

**Comment by grezniczek** [comment]
Hi @fhosking - this is a bug that has been fixed with 2.0.1. Please give the updated version a try.
